name: fairseq
channels:
  - pytorch
  - sandeepgadhwal
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.13.0=py37h06a4308_0
  - aiohttp=3.7.4.post0=py37h7f8727e_2
  - async-timeout=3.0.1=py37h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py37h06a4308_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cached-property=1.5.2=py_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py37h06a4308_0
  - chardet=4.0.0=py37h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - coverage=5.5=py37h27cfd23_2
  - cryptography=3.4.8=py37hd23ed53_0
  - cudatoolkit=11.1.1=h6406543_8
  - dataclasses=0.8=pyh6d0b6a4_7
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.36.1=py37h2157cd5_1
  - h5py=3.2.1=py37h6c542dc_0
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py37h06a4308_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.1=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.4=py37h06a4308_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py37h27cfd23_1
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.1=py37ha9443f7_2
  - multidict=5.1.0=py37h27cfd23_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.2=py37h2d18471_0
  - numpy-base=1.20.2=py37hfae3a4d_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.2.0=py37he98fc37_0
  - pip=21.1.2=py37h06a4308_0
  - protobuf=3.17.2=py37h295c915_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=2.1.0=py37h06a4308_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h12debd9_4
  - pytorch=1.9.0=py3.7_cuda11.1_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.6.2=py37had2a1c9_1
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.35.4=hdfb4753_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.0=py37hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.10.0=py37_cu111
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py37h27cfd23_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - audioread==2.1.9
    - cffi==1.14.5
    - cycler==0.11.0
    - cython==0.29.23
    - decorator==5.1.0
    - editdistance==0.5.3
    - hydra-core==1.0.6
    - importlib-resources==5.1.4
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - librosa==0.8.1
    - llvmlite==0.37.0
    - matplotlib==3.4.3
    - numba==0.54.1
    - omegaconf==2.0.6
    - packaging==21.2
    - pandas==1.3.4
    - pooch==1.5.2
    - portalocker==2.0.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==5.4.1
    - regex==2021.4.4
    - resampy==0.2.2
    - sacrebleu==1.5.1
    - scikit-learn==1.0.1
    - soundfile==0.10.3.post1
    - threadpoolctl==3.0.0
    - torchaudio==0.9.0
    - tqdm==4.61.1
    - zipp==3.4.1
prefix: /home/smg/cooper/miniconda3/envs/fairseq
